# Generated by Django 5.1.3 on 2024-11-24 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("herro", "0004_all_perfs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="All_Perfs",
            new_name="All_Perf",
        ),
    ]
